name: Update Source

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
      continue-on-error: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: true

    - name: Run scraper script
      run: python scraper.py
      continue-on-error: true

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: Shisuiicaro/Scraper
        path: target-repo
        token: ${{ secrets.GH_TOKEN }}
        ref: update
      continue-on-error: true

    - name: Copy and commit files
      run: |
        cp shisuyssource.json target-repo/
        cd target-repo
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add shisuyssource.json
        git commit -m "Update shisuyssource.json [skip ci]"
        git push origin update
      continue-on-error: true