name: Validate Source

on:
  workflow_run:
    workflows: ["Update Source"]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
      continue-on-error: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: true

    - name: Run validation script
      run: python validate.py
      continue-on-error: true

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: Shisuiicaro/scraper
        path: target-repo
        token: ${{ secrets.GH_TOKEN }}
        ref: update
      continue-on-error: true

    - name: Copy and commit validated files
      run: |
        cp validated.json target-repo/
        cd target-repo
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add validated.json
        git commit -m "Update validated.json [skip ci]"
        git push origin update
      continue-on-error: true
